[package]
name = "xdx-vst"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
nih_plug = { git = "https://github.com/robbert-vdh/nih-plug.git" }
nih_plug_egui = { git = "https://github.com/robbert-vdh/nih-plug.git" }
parking_lot = "0.12"
rfd = "0.14"
xdx-synth = { path = "../xdx-synth" }
xdx-core = { path = "../xdx-core" }
